version: "2"

run:
  concurrency: 8
  timeout: 10m
  tests: true

output:
  format: colored-line-number

linters-settings:
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - unused

issues:
  exclude-rules:
    - path: .*\.pb\.go$
    - path: .*\.pb\.gw\.go$
    - path: ^bin/
    - path: ^vendor/
    - path: ^var/
    - path: ^tmp/
    - path: ^\.cache/
    - text: G104 # _ instead of err checks
    - text: exported func .* returns unexported type .*
    - text: should have a package comment
    - text: don't use an underscore in package name
