version: "2"

run:
  timeout: 10m
  skip-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gosec
    - govet
    - ineffassign
    - revive
    - unused

linters-settings:
  govet:
    check-shadowing: true
  goconst:
    min-len: 2
    min-occurrences: 2

issues:
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
    - text: "G104"
      linters:
        - gosec
    - text: "exported func .* returns unexported type"
      linters:
        - revive
    - text: "should have a package comment"
      linters:
        - revive
    - text: "don't use an underscore in package name"
      linters:
        - revive