filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /app/logs/app.log
    json.keys_under_root: true
    json.add_error_key: true
    json.message_key: msg

output.logstash:
  hosts: ["logstash:5044"]