-- +goose Up
create table if not exists user_info (
    id int generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    is_admin bool not null,
    created_at timestamp not null default now(),
    updated_at timestamp
);

-- +goose Down
drop table user_info;
